### ISSUE TITLE
Project Management is not Resilient to the Card Already on the Board

### ISSUE THREAD

**Issue by bdarfler** [honeycombio/oss-management#9]
The project management action should check if the card is already on the board and then either move or create the card as needed.

**Comment by vreynolds** [comment]
Haven't felt the pain enough to do anything about it in a year.

**Comment by robbkidd** [comment]
Revisited this issue today in discussion.

> Project automation to create a card on the board for a new issue or PR will fail if the issue/PR author added it to the project manually already.

[Grug](https://grugbrain.dev/) says, "don't do that; let automation do that." The fix is more complicated than retraining ourselves to let automation automate.
